from google.appengine.ext import ndb
import webapp2
import json
import logging
'''
Boat
{ "id":"abc123", #this should be automatically generated by your API and should probably be a string
"name": "Sea Witch", #The name of the boat, a string
"type":"Catamaran", #The type of boat, power boat, sailboat, catamaran etc. a string
"length":28, #The length of the boat
"at_sea":false #A boolean indicating if the boat is at sea or not
}
Slip
{ "id":"123abc", #A string generated by your API
"number": 5, #The the slip number, essentially the human understandable identifier
"current_boat":"abc555",  #The id of the current boat, null if empty
"arrival_date":"1/1/2015", #A string indicating the date the boat arrived in the slip
"departure_history":[{"departure_date":"11/4/2014","departed_boat":"123aaa"}...] #Optional for 5% extra credit a list of the dates that previous boats departed the slip
}
'''
class Boat(ndb.Model):
    id = ndb.StringProperty()
    name = ndb.StringProperty()
    type = ndb.StringProperty()
    length = ndb.IntegerProperty()
    at_sea = ndb.BooleanProperty()

class Slip(ndb.Model):
    id = ndb.StringProperty()
    number = ndb.IntegerProperty()
    current_boat = ndb.StringProperty()
    arrival_date = ndb.StringProperty()
    departure_history = ndb.JsonProperty()

class BoatHandler(webapp2.RequestHandler):
    def post(self):
        boat_data = json.loads(self.request.body)
        new_boat = Boat(name=boat_data['name'], type=boat_data['type'],
                        length=boat_data['length'],at_sea=True)
        new_boat.put()
        new_boat.id = new_boat.key.urlsafe()
        new_boat.put()
        boat_dict = new_boat.to_dict()
        boat_dict['_self'] = "/boat/"+new_boat.key.urlsafe()
        self.response.write(json.dumps(boat_dict))
    def get(self, id=None):
        #Returning boat entity by identifier
        if id:
            b = ndb.Key(urlsafe=id).get()
            b_d = b.to_dict()
            b_d['self'] = "/boat" + id
            self.response.write(json.dumps(b.to_dict()))
        else:
            #Returning all boat entities
            self.response.write(json.dumps([b.to_dict() for b in Boat.query().fetch()]))

class SlipHandler(webapp2.RequestHandler):
    def post(self):
        slip_data = json.loads(self.request.body)
        new_slip = Slip(number=slip_data['number'])
        new_slip.put()
        new_slip.id = new_slip.key.urlsafe()
        new_slip.put()
        slip_dict = new_slip.to_dict()
        slip_dict['self'] = '/slip/' + new_slip.key.urlsafe()
        self.response.write(json.dumps(slip_dict))
    def get(self, id=None):
        if id:
            s = ndb.Key(urlsafe=id).get()
            s_d = s.to_dict()
            s_d['self'] = "/slip" + id
            self.response.write(json.dumps(s.to_dict()))
        else:
            #Returning all slip entities
            self.response.write(json.dumps([s.to_dict() for s in Slip.query().fetch()]))
    def delete(self, id=None):
        if id:
            s = ndb.Key(urlsafe=id).get()
            #Checking if boat needs updating to at sea
            if s.current_boat != null:
                b = ndb.Key(s.current_boat).get()
                b.at_sea = True
            s.key.delete()
            self.response.write("Slip "+id+" deleted")
    def patch(self, id=None):
        if id:
            s = ndb.Key(urlsafe=id).get()
            slip_data = json.loads(self.request.body)
            #managing arrival
            if s.current_boat == null:
                b = ndb.Key(s.current_boat).get()
                b.at_sea = False
            else:
                #returning 403
                response.write("Error: 403 Forbidden message")
                response.set_status(403)

            for key in slip_data:
                setattr(s, key, slip_data[key])
            s.put()
            slip_dict = s.to_dict()
                


class MainPage(webapp2.RequestHandler):
    def get(self):
        self.response.write("Marina API(REST Planning and Implementation) by Sam Hudson for CS496")
allowed_methods = webapp2.WSGIApplication.allowed_methods
new_allowed_methods = allowed_methods.union(('PATCH',))
webapp2.WSGIApplication.allowed_methods = new_allowed_methods
    
app = webapp2.WSGIApplication([
    ('/', MainPage),
    ('/slip', SlipHandler),
    ('/slip/(.*)', SlipHandler),    
    ('/boat', BoatHandler),
    ('/boat/(.*)', BoatHandler)
], debug=True)